enzi_version = "0.3"

[package]
name = "adapters"
version = "0.2.4"
authors = [ "Mot Yu",]

[filesets.rtl]
files = [
    "./rtl/ahb_lite_adapter.sv",
    "./rtl/apb_adapter.sv",
    "./rtl/axi4_lite_adapter_old.sv",
    "./rtl/axi4_lite_adapter.sv"
]

[dependencies.common_cells]
path =  "/home/motyu/ic_projs/common_cells"
version = "0.1.3"

[targets.build]
default_tool = "ies"
toplevel = "ahb_lite_adapter"
filesets = ["rtl"]
